swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    delivery_addresses: ['testphp59150@gmail.com']
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.gmail.com
    username:   testphp59150@gmail.com
    password:   testphp59150!
    port:   465
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

