swiftmailer:
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }
    transport:  smtp
    encryption: ssl
    auth_mode:  login
    host:       smtp.sendgrid.net
    username:   apikey
    password:   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
    port:   465
    stream_options:
        ssl:
            allow_self_signed: true
            verify_peer: false
            verify_peer_name: false

